import {
  gray,
  blue,
  green,
  yellow,
  orange,
  red,
  purple,
  pink,
  lightblue,
  cyan,
  magenta,
} from "waver-color";

export const colors = {
  black: "#111",
  white: "#fff",
  gray: gray.colors().map((c) => c.hex()),
  blue: blue.colors().map((c) => c.hex()),
  green: green.colors().map((c) => c.hex()),
  yellow: yellow.colors().map((c) => c.hex()),
  orange: orange.colors().map((c) => c.hex()),
  red: red.colors().map((c) => c.hex()),
  purple: purple.colors().map((c) => c.hex()),
  pink: pink.colors().map((c) => c.hex()),
};

export const WaverThemes = {
  primary: [lightblue.get("6d").hex(), lightblue.get("7d").hex()],
  foreground: ["#ccd6dbee", "#35393b"],
  activeForeground: ["#aab8bf", "#aab8bf"],
  secondaryForeground: ["#d5dbde90", "#35393b90"],
  ignored: ["#d5dbde50", "#35393b50"],
  faded: ["#d5dbde10", "#35393b10"],
  border: ["#141414", "#ebebeb"],
  background: ["#0f0f0f", "#ffffff"],
  activeBackground: ["#161616", "#f7f7f7"],
  selectionBackground: ["#eeeeee24", "#22222224"],
  selectionBackgroundActive: ["#eeeeee24", "#22222224"],
  selectionBackgroundInActive: ["#eeeeee16", "#22222216"],

  comment: ["#808080dd", "#aaaaaaff"],
  string: [gray.get("3").hex(), gray.get("6").hex()],
  variable: [pink.get("6d").hex(), pink.get("7d").hex()],
  keyword: [lightblue.get("6d").hex(), lightblue.get("7d").hex()],
  number: [green.get("6dd").hex(), green.get("7dd").hex()],
  boolean: [green.get("6dd").hex(), green.get("7dd").hex()],
  operator: [yellow.get("6dd").hex(), yellow.get("7dd").hex()],
  function: [yellow.get("6dd").hex(), yellow.get("7dd").hex()],
  constant: [green.get("6dd").hex(), green.get("7dd").hex()],
  class: [cyan.get("6dd").hex(), cyan.get("7dd").hex()],
  interface: [cyan.get("6dd").hex(), cyan.get("7dd").hex()],
  type: [cyan.get("6dd").hex(), cyan.get("7dd").hex()],
  builtin: [green.get("6dd").hex(), green.get("7dd").hex()],
  property: [lightblue.get("6d").hex(), lightblue.get("7d").hex()],
  namespace: [lightblue.get("6d").hex(), lightblue.get("7d").hex()],
  punctuation: [gray.get("3").hex(), gray.get("6").hex()],
  decorator: [red.get("6dd").hex(), red.get("7dd").hex()],
  regex: [red.get("6dd").hex(), red.get("7dd").hex()],

  gray: [gray.get("3").hex(), gray.get("6").hex()],
  green: [green.get("5d").hex(), green.get("7d").hex()],
  cyan: [cyan.get("5d").hex(), cyan.get("7d").hex()],
  blue: [lightblue.get("5d").hex(), lightblue.get("7d").hex()],
  red: [red.get("5d").hex(), red.get("7d").hex()],
  orange: [orange.get("5d").hex(), orange.get("7d").hex()],
  yellow: [yellow.get("5d").hex(), yellow.get("7d").hex()],
  magenta: [magenta.get("5d").hex(), magenta.get("7d").hex()],
} satisfies Record<string, [string, string] | string>;
