import {
  gray,
  blue,
  green,
  yellow,
  orange,
  red,
  purple,
  pink,
  lightblue,
  cyan,
  lightgreen,
  lightyellow,
} from "waver-color";

export const colors = {
  black: "#111",
  white: "#fff",
  gray: gray.colors().map((c) => c.hex()),
  blue: blue.colors().map((c) => c.hex()),
  green: green.colors().map((c) => c.hex()),
  yellow: yellow.colors().map((c) => c.hex()),
  orange: orange.colors().map((c) => c.hex()),
  red: red.colors().map((c) => c.hex()),
  purple: purple.colors().map((c) => c.hex()),
  pink: pink.colors().map((c) => c.hex()),
};

export const WaverThemes = {
  primary: [lightblue.get("5d").hex(), lightblue.get("6d").hex()],

  foreground: ["#dbd7caee", "#393a34"],
  activeForeground: ["#bfbaaa", "#4e4f47"],
  secondaryForeground: ["#dedcd590", "#393a3490"],

  ignored: ["#dedcd550", "#393a3450"],
  faded: ["#dedcd510", "#393a3410"],
  border: ["#191919", "#f0f0f0"],

  background: ["#0f0f0f", "#ffffff"],
  activeBackground: ["#161616", "#f7f7f7"],
  selectionBackground: ["#eeeeee24", "#22222224"],
  selectionBackgroundActive: ["#eeeeee24", "#22222224"],
  selectionBackgroundInActive: ["#eeeeee16", "#22222216"],

  comment: ["#808080dd", "#aaaaaaff"],
  string: [orange.get("5d").hex(), orange.get("6d").hex()],
  variable: [lightblue.get("5d").hex(), lightblue.get("6d").hex()],
  keyword: [pink.get("5d").hex(), pink.get("6d").hex()],
  number: [lightgreen.get("5d").hex(), lightgreen.get("6d").hex()],
  boolean: [cyan.get("5d").hex(), cyan.get("6d").hex()],
  operator: [orange.get("5d").hex(), orange.get("6d").hex()],
  function: [lightyellow.get("5d").hex(), lightyellow.get("6d").hex()],
  constant: [lightgreen.get("5d").hex(), lightgreen.get("6d").hex()],
  class: [lightgreen.get("5d").hex(), lightgreen.get("6d").hex()],
  interface: [lightgreen.get("5d").hex(), lightgreen.get("6d").hex()],
  type: [lightgreen.get("5d").hex(), lightgreen.get("6d").hex()],
  builtin: [blue.get("5d").hex(), blue.get("6d").hex()],
  property: [pink.get("5d").hex(), pink.get("6d").hex()],
  namespace: [pink.get("5d").hex(), pink.get("6d").hex()],
  punctuation: [gray.get("5d").hex(), gray.get("6d").hex()],
  decorator: [red.get("5d").hex(), red.get("6d").hex()],
  regex: [red.get("5d").hex(), red.get("6d").hex()],

  green: [lightgreen.get("5d").hex(), green.get("6d").hex()],
  cyan: [cyan.get("5d").hex(), cyan.get("6d").hex()],
  blue: [lightblue.get("5d").hex(), lightblue.get("6d").hex()],
  red: [red.get("5d").hex(), red.get("6d").hex()],
  orange: [orange.get("5d").hex(), orange.get("6d").hex()],
  yellow: [lightyellow.get("5d").hex(), yellow.get("6d").hex()],
  magenta: [pink.get("5d").hex(), pink.get("6d").hex()],
} satisfies Record<string, [string, string] | string>;
