import {
  gray,
  blue,
  green,
  yellow,
  orange,
  red,
  purple,
  pink,
  lightblue,
  cyan,
  magenta,
  lightgreen,
  lightyellow,
} from "waver-color";

export const colors = {
  black: "#111",
  white: "#fff",
  gray: gray().colors().slice(0, 10),
  blue: blue().colors().slice(0, 10),
  green: green().colors().slice(0, 10),
  yellow: yellow().colors().slice(0, 10),
  orange: orange().colors().slice(0, 10),
  red: red().colors().slice(0, 10),
  purple: purple().colors().slice(0, 10),
  pink: pink().colors().slice(0, 10),
};

export const WaverThemes = {
  primary: [cyan(4).saturated(), cyan(6).saturated()],

  foreground: ["#dbd7caee", "#393a34"],
  activeForeground: ["#bfbaaa", "#4e4f47"],
  secondaryForeground: ["#dedcd590", "#393a3490"],

  ignored: ["#dedcd550", "#393a3450"],
  faded: ["#dedcd510", "#393a3410"],
  border: ["#191919", "#f0f0f0"],

  background: ["#0f0f0f", "#ffffff"],
  activeBackground: ["#161616", "#f7f7f7"],
  selectionBackground: ["#eeeeee24", "#22222224"],
  selectionBackgroundActive: ["#eeeeee24", "#22222224"],
  selectionBackgroundInActive: ["#eeeeee16", "#22222216"],

  comment: ["#808080dd", "#aaaaaaff"],
  string: [orange(4).saturated(), gray(6).saturated()],
  variable: [lightblue(4).saturated(), lightblue(6).saturated()],
  keyword: [pink().saturated(), pink(6).saturated()],
  number: [lightgreen(4).saturated(), lightgreen(6).saturated()],
  boolean: [cyan(4).saturated(), cyan(6).saturated()],
  operator: [orange(4).saturated(), orange(6).saturated()],
  function: [lightyellow(3).saturated(), lightyellow(6).saturated()],
  constant: [lightgreen(4).saturated(), lightgreen(6).saturated()],
  class: [green(4).saturated(), green(6).saturated()],
  interface: [green(4).saturated(), green(6).saturated()],
  type: [green(4).saturated(), green(6).saturated()],
  builtin: [purple().saturated(), purple(6).saturated()],
  property: [pink().saturated(), pink(6).saturated()],
  namespace: [pink().saturated(), pink(6).saturated()],
  punctuation: [gray(4).hex(), gray(6).hex()],
  decorator: [red().saturated(), red(6).saturated()],
  regex: [red().saturated(), red(6).saturated()],

  green: [green().saturated(), green(6).saturated()],
  cyan: [cyan().saturated(), cyan(6).saturated()],
  blue: [blue().saturated(), blue(6).saturated()],
  red: [red().saturated(), red(6).saturated()],
  orange: [orange().saturated(), orange(6).saturated()],
  yellow: [yellow().saturated(), yellow(6).saturated()],
  magenta: [magenta().saturated(), magenta(6).saturated()],
} satisfies Record<string, [string, string] | string>;
